target_x: 6.0
target_y: 0.0
debug_mode: true

# ==========================================
# 规划与控制参数 (Planner & Control)
# ==========================================
planner:
  takeoff_height: 0.7     # 起飞/巡航高度
  
  # --- 速度与加速度限制 ---
  max_speed: 0.6          # 最大飞行速度 (m/s)
  max_yaw_rate: 0.6        # [关键] 最大旋转角速度 (rad/s), 越小转弯越柔和
  yaw_smooth_weight: 0.5   # [关键] VFH角度低通滤波系数 (0.0~1.0), 越小越平滑但反应越慢

  # --- 避障与地图 ---
  uav_radius: 0.0         # 无人机碰撞半径
  safe_margin: 0.0        # 膨胀安全余量
  min_safe_dist: 0.1      # 紧急制动距离
  wall_radius: 0.10        # [关键] 墙体在地图上的物理厚度 (m)
  check_radius_buffer: 0.2 # 路径检查的额外余量
  
  # --- 算法参数 ---
  lookahead_dist: 1.5      # 前视距离
  astar_weight: 1.2        # A* 启发式权重
  replan_cooldown: 1.5     # 重规划冷却时间
  
  # --- 旋转门控 (防止建图重影) ---
  map_decay_rate: 3             # 平稳时的地图衰减率
  rotation_gating_threshold: 0.3 # [关键] 超过此角速度(rad/s)时停止建图

  # --- 任务航点 (根据你的网格图配置) ---
  # 假设起飞点为 (0,0)
  wp1: [4, 0.0]   # 左上角
  wp2: [4,-3.5]   # 穿门后
  wp3: [0.0, -3.5]   # 右下角
  wp4: [0.0,-6.0]   # 终点
    # ==========================================
  # [新增] 动态二维地图配置
  # ==========================================
  map_resolution: 0.05  # 栅格大小(米)
  map_width_m: 20.0    # 地图物理宽度(X)
  map_height_m: 20.0   # 地图物理长度(Y)
  map_origin_x: -5.0   # 设在起飞点后方 5 米
  map_origin_y: -10.0  # 设在起飞点右侧 10 米

# ==========================================
# 降落识别参数 (Scan & Land)
# ==========================================
scan_land:
 
  err_max: 0.3
  p_xy: 0.3
  vel_track_max: 0.4
  time_threshold: 3.0
  yolo_follow_kp: -0.5